# file generated by vcs-versioning
# don't change, don't track in version control
from __future__ import annotations

__all__ = [
    "__version__",
    "__version_tuple__",
    "version",
    "version_tuple",
    "__commit_id__",
    "commit_id",
]

version: str
__version__: str
__version_tuple__: tuple[int | str, ...]
version_tuple: tuple[int | str, ...]
commit_id: str | None
__commit_id__: str | None

__version__ = version = '26.6.25.dev139+gb78c50f02.d20260904'
__version_tuple__ = version_tuple = (26, 6, 25, 'dev139', 'gb78c50f02.d20260904')

__commit_id__ = commit_id = 'gb78c50f02'
