"""Public execution-kernel API for UCAgent's simulation and formal workflows."""

from .adapters import (
    FormalMcAdapter,
    PickerAdapter,
    PytestAdapter,
    SbyAdapter,
    ToolchainAdapter,
    UrgAdapter,
    VcFormalAdapter,
    VcsAdapter,
    VerdiArtifactAdapter,
    get_adapter,
    list_adapters,
    register_adapter,
)
from .driver import WorkflowDriver, WorkflowResult
from .input_closure import (
    InputClosure,
    InputClosureSecurityError,
    merge_input_closures,
    resolve_tcl_source_closure,
    resolve_vcs_filelist_closure,
)
from .license_probe import LicenseStatus, build_license_probe_request, classify_license_probe
from .manifest import ManifestVerificationError, verify_manifest
from .models import (
    Artifact,
    CommandSpec,
    CoverageMetric,
    ExecutionStatus,
    FormalProperty,
    FormalPropertyStatus,
    FsdbPliProfile,
    RunRequest,
    RunResult,
    SessionInput,
    TestResult,
    ToolchainProfile,
    VerificationStatus,
)
from .parsers import (
    ParsedOutput,
    parse_formal_log,
    parse_pytest_log,
    parse_urg_output,
    parse_urg_report,
    parse_uvm_log,
)
from .runner import DiskSpaceError, JobRunner, UnsupportedEnvironmentSetup


__all__ = [
    "Artifact",
    "CommandSpec",
    "CoverageMetric",
    "DiskSpaceError",
    "ExecutionStatus",
    "FormalMcAdapter",
    "FormalProperty",
    "FormalPropertyStatus",
    "FsdbPliProfile",
    "InputClosure",
    "InputClosureSecurityError",
    "JobRunner",
    "LicenseStatus",
    "ManifestVerificationError",
    "ParsedOutput",
    "PickerAdapter",
    "PytestAdapter",
    "RunRequest",
    "RunResult",
    "SessionInput",
    "SbyAdapter",
    "TestResult",
    "ToolchainAdapter",
    "ToolchainProfile",
    "UnsupportedEnvironmentSetup",
    "UrgAdapter",
    "VcFormalAdapter",
    "VcsAdapter",
    "VerdiArtifactAdapter",
    "VerificationStatus",
    "WorkflowDriver",
    "WorkflowResult",
    "build_license_probe_request",
    "classify_license_probe",
    "get_adapter",
    "list_adapters",
    "merge_input_closures",
    "parse_formal_log",
    "parse_pytest_log",
    "parse_urg_output",
    "parse_urg_report",
    "parse_uvm_log",
    "register_adapter",
    "resolve_tcl_source_closure",
    "resolve_vcs_filelist_closure",
    "verify_manifest",
]
