// Wrapper for {dut_name}
// Auto-generated by GenerateChecker tool
// Instances DUT and checker

module {dut_name_wrapper} (
  {port_decl}
);

  // ---------------------------------------------------------------------------
  // Clock/Reset Remapping (auto-generated)
  // Wrapper interface uses standard 'clk'/'rst_n'; internal wires map to RTL names.
  // ---------------------------------------------------------------------------
{clk_rst_remap}

  // ---------------------------------------------------------------------------
  // DUT Instantiation
  // ---------------------------------------------------------------------------
  {dut_name}{param_inst} dut (
    {dut_conns}
  );

  // ---------------------------------------------------------------------------
  // White-box Verification: Internal Signals Extraction
  // ---------------------------------------------------------------------------
  // [LLM-TODO]: Extract critical internal signals using 'dut.signal' paths.
  // Example: wire [4:0] dut_ptr = dut.ptr_reg;
  //          wire [3:0] dut_state = dut.fsm_state;

  // ---------------------------------------------------------------------------
  // Symbolic Indexing Logic (for Arrays/FIFOs/RegFiles)
  // ---------------------------------------------------------------------------
  // [LLM-TODO]: If the design has array-like storage, define fv_idx and mux.
  // input [INDEX_WIDTH-1:0] fv_idx; // Controlled by Formal Tool
  // wire [DATA_WIDTH-1:0] fv_mon_data = entries[fv_idx];

  // ---------------------------------------------------------------------------
  // Checker Instantiation
  // ---------------------------------------------------------------------------
  {dut_name}_checker{param_inst} checker_inst (
    {checker_conns}
    // [LLM-TODO]: Connect white-box and symbolic signals here
  );

endmodule
