"""Restricted Claude Code CLI requests and deterministic session-result validation."""

from __future__ import annotations

import json
from pathlib import Path
import re
from uuid import UUID

from .models import CommandSpec, ExecutionStatus, RunRequest, SessionInput, VerificationStatus
from .parsers import ParsedOutput


REQUIRED_FLAGS = ("--print", "--output-format", "--session-id", "--resume",
                  "--strict-mcp-config", "--mcp-config", "--tools", "--settings",
                  "--setting-sources", "--disable-slash-commands", "--permission-mode")
CAMPAIGN_TOOLS = ("read_input", "query_evidence", "submit_proposal", "request_run")
FORMAL_TOOLS = ("RoleInfo", "CurrentTips", "ReadTextFile", "EditTextFile", "Check", "Complete", "SetCurrentStageJournal")


def validate_cli_capabilities(help_text: str) -> list[str]:
    """Check documented visible flags; hidden SDK options need a real call probe.

    In particular, --max-turns is intentionally absent from some CLI help
    versions. The authenticated bounded-job acceptance also exercises it.
    """
    return [flag for flag in REQUIRED_FLAGS if flag not in help_text]


def isolation_settings(user_settings: Path, control_root: Path) -> dict:
    """Disable automatic execution without copying authentication or routing settings.

    The administrator must also inspect managed policy. CLI precedence cannot
    override enterprise-enforced hooks; such a deployment is not eligible for
    unattended campaigns until its administrator provides an isolated identity.
    """
    for parent in (control_root, *control_root.parents):
        for name in (".mcp.json", "CLAUDE.md", ".claude"):
            if name == ".claude" and parent / name == user_settings.parent:
                continue
            if (parent / name).exists():
                raise ValueError("Claude control directory must not inherit project customizations")
    settings = {}
    if user_settings.exists():
        if user_settings.is_symlink() or user_settings.stat().st_size > 2 * 1024**2:
            raise ValueError("Claude user settings require administrator isolation review")
        settings = json.loads(user_settings.read_text(encoding="utf-8"))
        if not isinstance(settings, dict):
            raise ValueError("Claude user settings must be a JSON object")
    plugins = settings.get("enabledPlugins", {})
    if not isinstance(plugins, dict):
        raise ValueError("Claude enabledPlugins must be an object")
    return {"disableAllHooks": True, "autoMemoryEnabled": False,
            "enabledPlugins": {name: False for name in plugins}}


def build_claude_request(*, workspace: Path, output_dir: Path, prompt_path: Path,
                         mcp_path: Path, settings_path: Path, session_id: str,
                         resume: bool, timeout_seconds: float = 600,
                         max_turns: int = 12, model: str | None = None,
                         tool_scope: str = "campaign") -> RunRequest:
    """Build argv-only invocation in a clean session with an exact persisted UUID.

    MCP configuration and isolation settings are generated by the platform, not
    accepted from imported repositories or supplied by the model.
    """
    if str(UUID(session_id)) != session_id:
        raise ValueError("session_id must be a canonical UUID")
    if not 1 <= max_turns <= 30:
        raise ValueError("max_turns must be between 1 and 30")
    if model is not None and not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._:/-]{0,199}", model):
        raise ValueError("model must be a bounded literal model identifier, not a CLI option")
    if tool_scope not in {"campaign", "formal"}:
        raise ValueError("tool_scope must be campaign or formal")
    names = CAMPAIGN_TOOLS if tool_scope == "campaign" else FORMAL_TOOLS
    allowed = ",".join("mcp__" + tool_scope + "__" + name for name in names)
    argv = ["claude", "--print", "--output-format", "stream-json", "--verbose",
            "--resume" if resume else "--session-id", session_id,
            "--strict-mcp-config", "--mcp-config", "{SESSION_DIR}/mcp.json",
            "--tools=", "--allowedTools", allowed, "--permission-mode", "dontAsk",
            "--setting-sources", "user", "--settings", "{SESSION_DIR}/policy.json",
            "--disable-slash-commands", "--max-turns", str(max_turns)]
    if model is not None:
        argv.extend(["--model", model])
    return RunRequest(
        workspace=workspace, output_dir=output_dir, resource_class="claude",
        command=CommandSpec(argv=argv, tool="claude", cwd=Path("{SESSION_DIR}"),
                            timeout_seconds=timeout_seconds),
        session_inputs=[SessionInput(source=prompt_path, destination=Path("prompt.txt")),
                        SessionInput(source=mcp_path, destination=Path("mcp.json")),
                        SessionInput(source=settings_path, destination=Path("policy.json"))],
        stdin_path=Path("prompt.txt"), memory_limit_bytes=2 * 1024**3,
        output_limit_bytes=16 * 1024**2, parser="claude",
        metadata={"adapter": "claude", "session_id": session_id, "resume": resume,
                  "model": model, "cacheable": False})


def parse_claude_output(text: str, *, return_code: int, session_id: str,
                        expected_model: str | None = None) -> ParsedOutput:
    """Accept one authentic-shaped terminal CLI result, never a verification claim."""
    result = None
    diagnostic = None
    observed_models = set()
    try:
        for line in text.splitlines():
            if not line.strip():
                continue
            event = json.loads(line)
            if not isinstance(event, dict) or not isinstance(event.get("type"), str):
                raise ValueError("invalid event envelope")
            observed_id = event.get("session_id")
            if observed_id is not None and observed_id != session_id:
                raise ValueError("session identity mismatch")
            if event["type"] == "system" and event.get("subtype") == "init":
                observed_models.add(event.get("model"))
            if event["type"] == "assistant":
                message = event.get("message")
                if not isinstance(message, dict):
                    raise ValueError("invalid assistant event")
                observed_models.add(message.get("model"))
            if event["type"] == "result":
                if result is not None or observed_id != session_id:
                    raise ValueError("missing or duplicate result identity")
                result = event
        if result is None:
            raise ValueError("no terminal result")
        if not isinstance(result.get("is_error"), bool):
            raise ValueError("result.is_error must be a boolean")
        if "modelUsage" in result:
            if not isinstance(result["modelUsage"], dict):
                raise ValueError("modelUsage must be an object")
            observed_models.update(result["modelUsage"])
        # Pinning a gateway model must also survive resume. These are reported
        # provider identities, not a cryptographic attestation of model weights.
        if result.get("permission_denials"):
            diagnostic = "claude_permission_denied"
        elif return_code or result["is_error"] or result.get("subtype") != "success":
            message = str(result.get("result", "")).casefold()
            diagnostic = ("claude_authentication_required" if any(x in message for x in ("not logged in", "authentication", "invalid api key"))
                          else "claude_rate_limited" if "rate limit" in message or "429" in message
                          else "claude_service_unavailable" if "503" in message or "service unavailable" in message
                          else "claude_budget_exhausted" if result.get("subtype") == "error_max_turns"
                          else "claude_turn_failed")
        elif expected_model and observed_models != {expected_model}:
            # CLI-generated API error messages may have a synthetic model label.
            # Only successful model output can be accepted, and must match exactly.
            diagnostic = "claude_model_mismatch"
    except (ValueError, TypeError):
        diagnostic = "claude_malformed_result"
    failure = {"error_code": diagnostic, "error": "Claude did not finish the approved session successfully.",
               "next_action": "Inspect bounded CLI evidence; repair login, permissions or session state before retrying."}
    if diagnostic == "claude_model_mismatch":
        failure.update({"error": "The requested model does not match the provider-reported model identity.",
                        "expected": {"model": expected_model},
                        "observed": {"models": sorted(str(value)[:200] for value in observed_models)[:10]},
                        "next_action": "Select an available gateway model explicitly and repeat the call with that model pinned; do not rename another model to match."})
    elif diagnostic == "claude_service_unavailable":
        failure.update(error="The configured model service is unavailable (HTTP 503).",
                       next_action="Keep the selected model and saved stage. Retry only after the service recovers; no verification result was inferred.")
    elif diagnostic == "claude_budget_exhausted":
        failure.update(error="The approved Agent turn budget was exhausted.",
                       next_action="Review the saved stage and tool evidence, then explicitly continue with a new bounded turn.")
    return ParsedOutput(
        execution_status=ExecutionStatus.ERROR if diagnostic else ExecutionStatus.COMPLETED,
        verification_status=VerificationStatus.UNKNOWN,
        diagnostics=[failure] if diagnostic else [])
